### ISSUE TITLE
Go proto import wrongly generated

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/api-clients#121]
Here the proto api refer to the rest of the proto:
https://github.com/vegaprotocol/api-clients/blob/develop/go/generated/code.vegaprotocol.io/vega/proto/api/trading.pb.go#L7

Although the generated path should most likely be something like this:
```
import "github.com/vegaprotocol/api-clients/go/generated/code.vegaprotocol.io/vega/proto"
```

**Comment by ashleyvega** [comment]
I think that `go_package` lines need to be updated, e.g.

https://github.com/vegaprotocol/api-clients/blob/5d73d0e82d023ef85ef8ddb55d830b04324f21db/proto/assets.proto#L5

**Comment by jeremyletang** [comment]
> I think that `go_package` lines need to be updated, e.g.
> 
> https://github.com/vegaprotocol/api-clients/blob/5d73d0e82d023ef85ef8ddb55d830b04324f21db/proto/assets.proto#L5

I would suppose so yes.
